### ISSUE TITLE
Unable to run Node.js SDK code

### ISSUE THREAD

**Issue by xamQrexii** [aspose-words-cloud/aspose-words-cloud-node#2]
var request = new PostDocumentSaveAsRequest({
              ^

TypeError: PostDocumentSaveAsRequest is not a constructor
    at Object.<anonymous> (/home/osama/Desktop/jumayr/jumayr-attachments/replace-text/app.js:33:15)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3

**Comment by dmitry-finozhenok** [comment]
Thank you for your request.
The current version of the SDK uses SaveAsRequest instead of PostDocumentSaveAsRequest, and the method name is saveAs instead of postDocumentSaveAs.
The README.md is updated to reflect current naming.
